#!/usr/bin/env python3
"""Stage the ChatArch Pages hub as a deployable static site."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

PUBLIC_FILES = [".nojekyll", "CNAME", "404.html", "index.html"]
ALIAS_MARKER = "Generated by scripts/generate_lowercase_aliases.py; do not edit by hand."


def is_generated_alias_dir(path: Path) -> bool:
    index = path / "index.html"
    if not path.is_dir() or not index.exists():
        return False
    return ALIAS_MARKER in index.read_text(encoding="utf-8", errors="ignore")


def build(repo_dir: Path, output_dir: Path) -> None:
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)

    for name in PUBLIC_FILES:
        source = repo_dir / name
        if source.exists():
            shutil.copy2(source, output_dir / name)

    for child in sorted(repo_dir.iterdir()):
        if is_generated_alias_dir(child):
            shutil.copytree(child, output_dir / child.name)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-dir", default=".")
    parser.add_argument("--output", default="site")
    args = parser.parse_args()

    repo_dir = Path(args.repo_dir).resolve()
    output_dir = Path(args.output)
    if not output_dir.is_absolute():
        output_dir = repo_dir / output_dir
    build(repo_dir, output_dir.resolve())
    print(f"staged static site at {output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
