#!/usr/bin/env python3
"""Generate lowercase project route aliases for the ChatArch Pages hub."""

from __future__ import annotations

import argparse
import html
import json
import re
import shutil
import sys
from pathlib import Path

OWNER = "ChatArch"
MARKER = "Generated by scripts/generate_lowercase_aliases.py; do not edit by hand."
INDEX_RE = re.compile(r"https://github\.com/ChatArch/([A-Za-z0-9_.-]+)")


def repo_names(index_html: str) -> list[str]:
    names = sorted(set(INDEX_RE.findall(index_html)))
    return [name for name in names if name != f"{OWNER}.github.io"]


def aliases_for(names: list[str]) -> dict[str, str]:
    return {name.lower(): name for name in names if name.lower() != name}


def render_alias_page(canonical: str) -> str:
    target = f"/{canonical}/"
    escaped_target = html.escape(target, quote=True)
    escaped_name = html.escape(canonical)
    return f"""<!doctype html>
<!-- {MARKER} -->
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <meta http-equiv=\"refresh\" content=\"0; url={escaped_target}\">
  <link rel=\"canonical\" href=\"{escaped_target}\">
  <title>Redirecting to {escaped_name}</title>
</head>
<body>
  <p>Redirecting to <a href=\"{escaped_target}\">{escaped_name}</a>.</p>
  <script>window.location.replace({json.dumps(target)} + window.location.search + window.location.hash);</script>
</body>
</html>
"""


def render_404(aliases: dict[str, str]) -> str:
    alias_lines = ",\n        ".join(
        f"{json.dumps(alias)}: {json.dumps(canonical)}"
        for alias, canonical in sorted(aliases.items())
    )
    return f"""<!doctype html>
<!-- {MARKER} -->
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>Page not found - ChatArch</title>
  <script>
    (function () {{
      var aliases = {{
        {alias_lines}
      }};
      var match = window.location.pathname.match(/^\\/([^/?#]+)(\\/.*)?$/);
      if (!match) return;
      var canonical = aliases[match[1].toLowerCase()];
      if (!canonical || match[1] === canonical) return;
      var rest = match[2] || '/';
      window.location.replace('/' + canonical + rest + window.location.search + window.location.hash);
    }}());
  </script>
</head>
<body>
  <h1>Page not found</h1>
  <p>The requested ChatArch page was not found.</p>
  <p>Project routes are case-sensitive. Try the canonical project path from <a href=\"/\">the ChatArch project map</a>.</p>
</body>
</html>
"""


def collect(repo_dir: Path) -> dict[str, str]:
    index_path = repo_dir / "index.html"
    if not index_path.exists():
        raise SystemExit("index.html is required before generating aliases")
    return aliases_for(repo_names(index_path.read_text(encoding="utf-8")))


def write_aliases(repo_dir: Path, aliases: dict[str, str]) -> list[Path]:
    written: list[Path] = []
    not_found = repo_dir / "404.html"
    not_found.write_text(render_404(aliases), encoding="utf-8")
    written.append(not_found)

    current_aliases = set(aliases)
    for child in repo_dir.iterdir():
        if not child.is_dir() or child.name in current_aliases:
            continue
        index = child / "index.html"
        if index.exists() and MARKER in index.read_text(encoding="utf-8", errors="ignore"):
            shutil.rmtree(child)

    for alias, canonical in sorted(aliases.items()):
        alias_dir = repo_dir / alias
        alias_dir.mkdir(exist_ok=True)
        alias_index = alias_dir / "index.html"
        alias_index.write_text(render_alias_page(canonical), encoding="utf-8")
        written.append(alias_index)
    return written


def check_aliases(repo_dir: Path, aliases: dict[str, str]) -> list[str]:
    stale: list[str] = []
    expected_404 = render_404(aliases)
    actual_404 = (repo_dir / "404.html").read_text(encoding="utf-8") if (repo_dir / "404.html").exists() else ""
    if actual_404 != expected_404:
        stale.append("404.html")

    for alias, canonical in sorted(aliases.items()):
        alias_index = repo_dir / alias / "index.html"
        expected = render_alias_page(canonical)
        actual = alias_index.read_text(encoding="utf-8") if alias_index.exists() else ""
        if actual != expected:
            stale.append(str(alias_index.relative_to(repo_dir)))
    return stale


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-dir", default=".")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    repo_dir = Path(args.repo_dir).resolve()
    aliases = collect(repo_dir)
    if args.check:
        stale = check_aliases(repo_dir, aliases)
        if stale:
            print("stale lowercase aliases:")
            for path in stale:
                print(f"- {path}")
            return 1
        print(f"lowercase aliases are current: {len(aliases)}")
        return 0

    write_aliases(repo_dir, aliases)
    print(f"generated {len(aliases)} lowercase project aliases")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
