#!/usr/bin/env python3
"""Validate the generated ChatArch Pages hub before CI/deploy."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

PRIVATE_NAME_GUARD = {
    "ChatClash",
    "ChatCube",
    "ChatJiXia",
    "ChatMath",
    "ChatNLP",
    "ChatSage",
    "demo-repository",
}
PUBLIC_FILES = ["index.html", "404.html", "README.md", "CNAME", ".nojekyll"]
ALIAS_RE = re.compile(r'"([a-z0-9_.-]+)": "([A-Za-z0-9_.-]+)"')
ALIAS_MARKER = "Generated by scripts/generate_lowercase_aliases.py; do not edit by hand."


def fail(message: str) -> None:
    raise SystemExit(message)


def public_text_files(repo_dir: Path) -> list[Path]:
    files = [repo_dir / name for name in PUBLIC_FILES if (repo_dir / name).is_file()]
    for child in repo_dir.iterdir():
        if child.is_dir():
            index = child / "index.html"
            if index.exists() and ALIAS_MARKER in index.read_text(encoding="utf-8", errors="ignore"):
                files.append(index)
    return files


def main() -> int:
    repo_dir = Path(__file__).resolve().parents[1]

    for name in PUBLIC_FILES:
        if not (repo_dir / name).exists():
            fail(f"missing required public file: {name}")

    cname = (repo_dir / "CNAME").read_text(encoding="utf-8").strip()
    if cname != "arch.gh.wzhecnu.cn":
        fail(f"unexpected CNAME: {cname}")

    subprocess.run(
        [sys.executable, str(repo_dir / "scripts" / "generate_lowercase_aliases.py"), "--check"],
        cwd=repo_dir,
        check=True,
    )

    not_found = (repo_dir / "404.html").read_text(encoding="utf-8")
    aliases = dict(ALIAS_RE.findall(not_found))
    if len(aliases) < 20:
        fail(f"too few lowercase aliases found: {len(aliases)}")

    for alias, canonical in aliases.items():
        if alias != canonical.lower():
            fail(f"alias key does not match canonical lowercase form: {alias} -> {canonical}")
        alias_index = repo_dir / alias / "index.html"
        if not alias_index.exists():
            fail(f"missing alias page: {alias_index.relative_to(repo_dir)}")
        alias_text = alias_index.read_text(encoding="utf-8")
        if f"/{canonical}/" not in alias_text:
            fail(f"alias page does not point to canonical path: {alias}")

    for path in public_text_files(repo_dir):
        text = path.read_text(encoding="utf-8", errors="ignore")
        for name in PRIVATE_NAME_GUARD:
            if name in text:
                fail(f"private/internal guard name leaked in {path.relative_to(repo_dir)}: {name}")

    print(f"validated ChatArch Pages hub: {len(aliases)} lowercase aliases")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
