#!/usr/bin/env python3
"""Validate the generated ChatArch Pages hub before CI/deploy."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

FORBIDDEN_LITERAL_GUARD = {
    "demo-repository",
}
FORBIDDEN_TEXT_PATTERNS = {
    "github_pat": re.compile(r"github_pat_[A-Za-z0-9_]+"),
    "classic_pat": re.compile(r"ghp_[A-Za-z0-9_]+"),
    "authorization_header": re.compile(r"Authorization\\s*:", re.I),
    "bearer_token": re.compile(r"Bearer\\s+[A-Za-z0-9._-]+", re.I),
    "private_key": re.compile(r"BEGIN (?:RSA |OPENSSH |EC |DSA )?PRIVATE KEY"),
    "private_ip_172_23": re.compile(r"172\\.23\\."),
    "private_ip_192_168": re.compile(r"192\\.168\\."),
    "localhost": re.compile(r"(?:127\\.0\\.0\\.1|localhost)", re.I),
    "local_home_path": re.compile(r"(?:/home/zhihong|/Users/rexwzh)"),
}
PUBLIC_FILES = ["index.html", "404.html", "README.md", "CNAME", ".nojekyll"]
ALIAS_RE = re.compile(r'"([a-z0-9_.-]+)": "([A-Za-z0-9_.-]+)"')
ALIAS_MARKER = "Generated by scripts/generate_lowercase_aliases.py; do not edit by hand."


def fail(message: str) -> None:
    raise SystemExit(message)


def public_text_files(repo_dir: Path) -> list[Path]:
    files = [repo_dir / name for name in PUBLIC_FILES if (repo_dir / name).is_file()]
    for child in repo_dir.iterdir():
        if child.is_dir():
            index = child / "index.html"
            if index.exists() and ALIAS_MARKER in index.read_text(encoding="utf-8", errors="ignore"):
                files.append(index)
    return files


def main() -> int:
    repo_dir = Path(__file__).resolve().parents[1]

    for name in PUBLIC_FILES:
        if not (repo_dir / name).exists():
            fail(f"missing required public file: {name}")

    cname = (repo_dir / "CNAME").read_text(encoding="utf-8").strip()
    if cname != "arch.gh.wzhecnu.cn":
        fail(f"unexpected CNAME: {cname}")

    subprocess.run(
        [sys.executable, str(repo_dir / "scripts" / "generate_lowercase_aliases.py"), "--check"],
        cwd=repo_dir,
        check=True,
    )

    not_found = (repo_dir / "404.html").read_text(encoding="utf-8")
    aliases = dict(ALIAS_RE.findall(not_found))
    if len(aliases) < 20:
        fail(f"too few lowercase aliases found: {len(aliases)}")

    for alias, canonical in aliases.items():
        if alias != canonical.lower():
            fail(f"alias key does not match canonical lowercase form: {alias} -> {canonical}")
        alias_index = repo_dir / alias / "index.html"
        if not alias_index.exists():
            fail(f"missing alias page: {alias_index.relative_to(repo_dir)}")
        alias_text = alias_index.read_text(encoding="utf-8")
        if f"/{canonical}/" not in alias_text:
            fail(f"alias page does not point to canonical path: {alias}")

    for path in public_text_files(repo_dir):
        text = path.read_text(encoding="utf-8", errors="ignore")
        for literal in FORBIDDEN_LITERAL_GUARD:
            if literal in text:
                fail(f"forbidden public literal leaked in {path.relative_to(repo_dir)}: {literal}")
        for label, pattern in FORBIDDEN_TEXT_PATTERNS.items():
            if pattern.search(text):
                fail(f"forbidden public-safety pattern leaked in {path.relative_to(repo_dir)}: {label}")

    print(f"validated ChatArch Pages hub: {len(aliases)} lowercase aliases")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
